name: dida-task
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.05.30=hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.9=hca72f7f_0
  - pip=23.1.2=py310hecd8cb5_0
  - python=3.10.11=h5ee71fb_3
  - readline=8.2=hca72f7f_0
  - setuptools=67.8.0=py310hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - wheel=0.38.4=py310hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - anyio==3.7.0
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cffi==1.15.1
    - comm==0.1.3
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - fonttools==4.40.0
    - fqdn==1.5.1
    - idna==3.4
    - ipykernel==6.23.3
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpointer==2.4
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.3.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.6.3
    - jupyter-server==2.7.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==3.0.1
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.6.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.25.0
    - opencv-python==4.7.0.72
    - overrides==7.3.1
    - packaging==23.1
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.8.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.15.1
    - pyparsing==3.1.0
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tornado==6.3.2
    - traitlets==5.9.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - widgetsnbextension==4.0.7
prefix: /Users/abhirupghosh/opt/anaconda3/envs/dida-task
